# Generated by Django 4.2 on 2023-10-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_reviews_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='book_samples/'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
